#!/bin/sh
### Dependencies are gamemode and wine with fsync patches ###

# Audio Samplerate Override (i.e. 44100,48000,88200)
SAMPLERATE=48000
# Buffer Period Blocksize (i.e 64,128,256)
BUFFERSIZE=256
# Path To DAW Binary (i.e. /usr/bin/ardour6)
DAW_BIN=/usr/bin/ardour6

## Set Samplerate and Blocksize
pw-metadata -n settings 0 clock.force-rate ${SAMPLERATE}
pw-metadata -n settings 0 clock.force-quantum ${BUFFERSIZE}

## Start Feral Gamemode To Boost Thread Priorities for DAW
WINEFSYNC=1 gamemoderun $DAW_BIN

## Set Samplerate and Blocksize Back To Default Settings
pw-metadata -n settings 0 clock.force-rate 0
pw-metadata -n settings 0 clock.force-quantum 0

## Stop Feral Gamemode
pkill -9 gamemoded
